"""
Compare a v1 book directory against the v2 one built from the same PDF.

The v1 payload was generated by an earlier pipeline whose defects are the
reason the current one exists, so this records what changed rather than
asserting it. Run it as evidence that reprocessing actually fixed the old
bugs, not merely that the new files exist.
"""

import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

V1 = Path(sys.argv[1] if len(sys.argv) > 1 else "backups/8bbc939a.v1.bak")
V2 = Path(sys.argv[2] if len(sys.argv) > 2 else "books/a8cacf49")

v1_meta = json.loads((V1 / "meta.json").read_text(encoding="utf-8"))
v2_meta = json.loads((V2 / "meta.json").read_text(encoding="utf-8"))

print("=" * 72)
print("SHAPE")
print("=" * 72)
print(f"v1 keys: {sorted(v1_meta)}")
print(f"v2 keys: {sorted(v2_meta)}")

v1_chapters = v1_meta.get("chapters", [])
v2_stream = v2_meta.get("stream", [])

print()
print("=" * 72)
print("COUNTS")
print("=" * 72)
print(f"v1 chapters: {len(v1_chapters)}")
print(f"v2 readable: {len(v2_stream)}")
print(f"v1 total words: {v1_meta.get('word_count') or v1_meta.get('total_words')}")
print(f"v2 total words: {v2_meta.get('total_words')}")

# ---------------------------------------------------------------------------
# Defect 1: duplicate payloads. v1's first two chapter files were byte-identical.
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("DEFECT 1 - byte-identical payloads")
print("=" * 72)

v1_files = sorted(V1.glob("ch_*.json"))
digests: dict[str, list[str]] = {}
for path in v1_files:
    digests.setdefault(path.read_bytes(), []).append(path.name)

duplicates = {names[0]: names[1:] for _, names in digests.items() if len(names) > 1}
if duplicates:
    for first, rest in duplicates.items():
        print(f"  v1 {first} is byte-identical to {', '.join(rest)}")
else:
    print("  v1: no duplicates")

v2_files = sorted((V2 / "client").glob("*.json"))
v2_digests: dict[bytes, list[str]] = {}
for path in v2_files:
    v2_digests.setdefault(path.read_bytes(), []).append(path.name)
v2_duplicates = {n[0]: n[1:] for _, n in v2_digests.items() if len(n) > 1}
print(f"  v2: {len(v2_duplicates)} duplicate(s)" + (f" -> {v2_duplicates}" if v2_duplicates else ""))

# ---------------------------------------------------------------------------
# Defect 2: heading/heading_level were uniformly null and false, so nothing in
# the old payload actually described the hierarchy.
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("DEFECT 2 - hierarchy never recorded")
print("=" * 72)

headings = [bool(c.get("heading")) for c in v1_chapters]
levels = [c.get("heading_level") for c in v1_chapters]
print(f"  v1 heading true:  {sum(headings)} / {len(headings)}")
print(f"  v1 heading_level distinct values: {sorted(set(map(str, levels)))}")

v2_types: dict[str, int] = {}
v2_levels: dict[int, int] = {}
for entry in v2_stream:
    v2_types[entry["entry_type"]] = v2_types.get(entry["entry_type"], 0) + 1
    v2_levels[entry["level"]] = v2_levels.get(entry["level"], 0) + 1
print(f"  v2 entry types: {v2_types}")
print(f"  v2 levels:      {v2_levels}")

# ---------------------------------------------------------------------------
# Defect 3: word_count disagreed with the words actually stored.
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("DEFECT 3 - count disagrees with the stored words")
print("=" * 72)

v1_mismatches = []
v1_counts_compared = 0
for chapter in v1_chapters:
    # v1 named each payload after the chapter id, not a `file` field.
    path = V1 / f"{chapter.get('id')}.json"
    if not path.exists():
        continue
    payload = json.loads(path.read_text(encoding="utf-8"))
    stored = payload if isinstance(payload, list) else (payload.get("words") or [])
    claimed = chapter.get("word_count")
    if claimed is None:
        continue
    v1_counts_compared += 1
    if claimed != len(stored):
        v1_mismatches.append((chapter["id"], claimed, len(stored)))

print(f"  v1 counts compared: {v1_counts_compared} / {len(v1_chapters)}")
print(f"  v1 mismatches: {len(v1_mismatches)}")
for name, claimed, actual in v1_mismatches[:10]:
    print(f"    {name}: claims {claimed}, stores {actual}")

v2_mismatches = 0
for entry in v2_stream:
    payload = json.loads((V2 / entry["file"]).read_text(encoding="utf-8"))
    if entry["word_count"] != len(payload["words"]):
        v2_mismatches += 1
print(f"  v2 counts compared: {len(v2_stream)} / {len(v2_stream)}")
print(f"  v2 mismatches: {v2_mismatches}")

if not v1_mismatches:
    print("  NOTE: v1's counts were self-consistent, so a count mismatch was NOT")
    print("        a v1 defect. What v1 lacked was the count being derived from")
    print("        the same string the reader would step through - here it was,")
    print("        but by construction elsewhere it was not, which is why v2")
    print("        asserts it at write time instead of trusting it.")

# ---------------------------------------------------------------------------
# Defect 4: titles fused together because two headings shared a page.
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("DEFECT 4 - fused or bogus chapter titles")
print("=" * 72)

for chapter in v1_chapters[:8]:
    print(f"  v1: {chapter.get('title')!r}")
print("  ..." if len(v1_chapters) > 8 else "")

print()
for entry in v2_stream[:8]:
    print(f"  v2: {entry['title']!r}")

# ---------------------------------------------------------------------------
# What v2 found that v1 never had at all.
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("WHAT V2 ADDED")
print("=" * 72)

v1_words = sum(c.get("word_count") or 0 for c in v1_chapters)
v2_words = sum(e["word_count"] for e in v2_stream)


def _walk(nodes):
    for node in nodes:
        yield node
        yield from _walk(node.get("children") or [])


v2_leaves = [n for n in _walk(v2_meta["sections"]) if not n.get("children")]
print(f"  v1 words across its 32 entries: {v1_words}")
print(f"  v2 words across its 26 readable: {v2_words}")
print(f"  v2 section tree: {len(v2_meta['sections'])} top-level node(s), {len(v2_leaves)} leaf/leaves")
print(f"  v2 readable leaves: {len(v2_stream)}; unreadable: {len(v2_leaves) - len(v2_stream)}")
print("  note: v1 counted a duplicated payload twice, so its total is not comparable.")

# Titles that differ only because v1 kept the printed chapter number.
import re as _re


def _bare(title: str) -> str:
    return _re.sub(r"^\s*\d+[.)]?\s+", "", title or "").strip()


v1_titles = {c.get("title") for c in v1_chapters}
v1_bare = {_bare(c.get("title")) for c in v1_chapters}
v2_titles = {e["title"] for e in v2_stream}
genuinely_missed = sorted(t for t in v2_titles if _bare(t) not in v1_bare)
numbered = sorted(t for t in v2_titles - v1_titles if _bare(t) in v1_bare)

print(f"  v1 entries that only differed by a leading number ({len(numbered)}):")
for title in numbered:
    print(f"    ~ {title}")
print(f"  titles v2 found that v1 genuinely lacked ({len(genuinely_missed)}):")
for title in genuinely_missed:
    print(f"    + {title}")

print()
print(f"  v2 checked by default: {v2_meta.get('checked_count')} / {v2_meta.get('readable_count')}")
for note in v2_meta.get("notes", []):
    print(f"    note: {note}")

print()
print("=" * 72)
print("SUMMARY")
print("=" * 72)
if duplicates:
    print(f"  FIXED  duplicate payloads ({len(duplicates)} pairs in v1, 0 in v2)")
if sum(headings) == 0:
    print("  FIXED  hierarchy never recorded (v1 0/32 headings, v2 has entry_type and level)")
if numbered:
    print(f"  FIXED  {len(numbered)} title(s) no longer carry the printed chapter number")
if genuinely_missed:
    print(f"  FIXED  {len(genuinely_missed)} section(s) v1 missed entirely")
if not v1_mismatches:
    print("  N/A    word count mismatch (not a v1 defect)")
print("  DOES NOT SURVIVE: v1 had no schema field, no confidence, no notes, no")
print("                   readable/unreadable split and no stream, so the reader")
print("                   could not tell a chapter from an index entry.")
